---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/cfn-nag
    tag: latest

inputs:
  - name: source
outputs:
  - name: results_cfn_lint

params:
  OUTPUT_DIR: results_cfn_lint/reports
  GENERATE_REPORT_AND_CONTINUE: # Set this to true if you do not want the job to exit with error, but still produce the report

run:
  path: source/scripts/cfn_nag.sh
