AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda to create/run crawler on object creation at raw, curated or transformed s3 buckets

Parameters:
  LambdaFunctionName:
    Type: String
    Default: lambda-trigger-glue-crawler
  LambdaRole:
    Type: String
    Default: lambda-service-role
  Subnets:
    Type: CommaDelimitedList
  Env:
    Type: String
  TeamTag:
    Type: String
    Default: itdna
  AWSTenant:
    Type: String
  crawleriamrole:
    Type: String

Resources:
  SMLogs:
    Type: AWS::Logs::LogGroup

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: Lambda to create/run crawler on object creation at raw, curated or transformed s3 buckets
      MemorySize: 128
      Timeout: 90
      CodeUri: !Sub ../../lambda/${LambdaFunctionName}
      FunctionName: !Ref LambdaFunctionName
      Environment:
        Variables:
          env: !Ref Env
          tenant: !Ref AWSTenant
          TeamTag: !Ref TeamTag
          crawler_iam_role: !Ref crawleriamrole

      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${LambdaRole}"
      Runtime: python3.8
      Tags:
        "vci:team" : !Ref TeamTag
        "env" : !Ref Env
        "tenant" : !Ref AWSTenant
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: vci-self-referencing-sg
        SubnetIds: !Ref Subnets

  LambdaPermission1:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*
