AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    185a76ca-ea3f-4dda-b384-6ee65cbe99e5:
      size:
        width: 60
        height: 60
      position:
        x: 406
        'y': 52
      z: 0
Resources:
  mycftest:
    Type: 'AWS::S3::Bucket'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 185a76ca-ea3f-4dda-b384-6ee65cbe99e5
